"""Build the prayer recordings and the app's manifest.

    python tools/build.py encode <raw_dir> <out_dir>
        Re-encode every <key>.mp3 in raw_dir to 64 kbps mono, 44.1 kHz, with
        ElevenLabs' metadata stripped, into out_dir. (Needs ffmpeg on PATH,
        or FFMPEG=/path/to/ffmpeg.)

    python tools/build.py manifest <folder> <commit>
        Print src/data/prayerAudio.ts for the app: one entry per prayer, the
        Hebrew and English file of each, pinned to <commit> of this repository
        so a URL never changes under a phone that cached it. Voices come from
        voices.json.

A file is named <prayer-id>.<he|en>.mp3. Durations are read from the files.
"""
import json, os, subprocess, sys
from mutagen.mp3 import MP3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = "michaelxedelstein/shmooze-audio"


def encode(raw_dir, out_dir):
    ffmpeg = os.environ.get("FFMPEG", "ffmpeg")
    os.makedirs(out_dir, exist_ok=True)
    for name in sorted(os.listdir(raw_dir)):
        if not name.endswith(".mp3"):
            continue
        subprocess.run(
            [ffmpeg, "-hide_banner", "-loglevel", "error", "-y", "-i", os.path.join(raw_dir, name),
             "-map_metadata", "-1", "-ac", "1", "-ar", "44100", "-b:a", "64k", os.path.join(out_dir, name)],
            check=True,
        )
        print("encoded", name)


def manifest(folder, commit):
    voices = json.load(open(os.path.join(ROOT, "voices.json")))
    files = sorted(n for n in os.listdir(os.path.join(ROOT, folder)) if n.endswith(".mp3"))
    prayers = {}
    for name in files:
        pid, lang, _ = name.rsplit(".", 2)
        prayers.setdefault(pid, {})[lang] = name
    m, f = voices["male"], voices["female"]
    out = [
        "/**",
        " * Studio recordings of the prayers.",
        " *",
        " * Every prayer has two files, the Hebrew and the English, rendered with",
        " * ElevenLabs and listed here by prayer id. Who reads follows the prayer's",
        " * gender tag: the prayers women say are read by a woman",
        f" * ({f['he']['name']} in Hebrew, {f['en']['name']} in English), every other prayer by a man",
        f" * ({m['he']['name']} in Hebrew, {m['en']['name']} in English). The English is a plain,",
        " * conversational read rather than a narrator's. The reader plays these when",
        " * it can reach them and falls back to the device voice when it can't.",
        " *",
        f" * Generated by tools/build.py in {REPO} from its",
        f" * {folder}/ folder — do not edit by hand.",
        " */",
        "export type PrayerRecording = {",
        "  url: string;",
        "  /** Length of the file, so the reader can follow along line by line. */",
        "  durationMs: number;",
        "  /** Who reads it: a woman for the prayers women say, a man for the rest. */",
        "  voice: 'male' | 'female';",
        "};",
        "",
        "export const PRAYER_AUDIO: Record<string, { he?: PrayerRecording; en?: PrayerRecording }> = {",
    ]
    for pid in sorted(prayers):
        out.append(f'  "{pid}": {{')
        for lang in ("he", "en"):
            name = prayers[pid].get(lang)
            if not name:
                continue
            voice = "female" if pid in voices["female"]["prayers"] else "male"
            ms = round(MP3(os.path.join(ROOT, folder, name)).info.length * 1000)
            url = f"https://raw.githubusercontent.com/{REPO}/{commit}/{folder}/{name}"
            out.append(f"    {lang}: {{ url: '{url}', durationMs: {ms}, voice: '{voice}' }},")
        out.append("  },")
    out.append("};")
    print("\n".join(out))


if __name__ == "__main__":
    cmd, *args = sys.argv[1:]
    {"encode": encode, "manifest": manifest}[cmd](*args)
